[package]
name = "rustmc"
version = "0.1.2"
edition = "2024"

[dependencies]
toml = "0.8.20"

[dependencies.serde]
version = "1.0.218"
features = ["derive"]

[dependencies.bevy]
version = "0.15.3"
features = []

[dependencies.sysx]
git = "https://github.com/lyric228/sysx"
