[package]
name = "rustmc"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "*"

[dependencies.serde]
version = "1.0.218"
features = ["derive"]

[dependencies.bevy]
version = "0.15.3"
features = []

[dependencies.sysx]
path = "../sysx"
